from __future__ import annotations

from datetime import timedelta

from homeassistant.const import Platform

DOMAIN = "tuya_ev_charger"

CONF_DEVICE_ID = "device_id"
CONF_LOCAL_KEY = "local_key"
CONF_PROTOCOL_VERSION = "protocol_version"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_SURPLUS_MODE_ENABLED = "surplus_mode_enabled"
CONF_SURPLUS_SENSOR_ENTITY_ID = "surplus_sensor_entity_id"
CONF_SURPLUS_SENSOR_INVERTED = "surplus_sensor_inverted"
CONF_SURPLUS_MODE = "surplus_mode"
CONF_SURPLUS_CURTAILMENT_SENSOR_ENTITY_ID = "surplus_curtailment_sensor_entity_id"
CONF_SURPLUS_CURTAILMENT_SENSOR_INVERTED = "surplus_curtailment_sensor_inverted"
CONF_SURPLUS_LINE_VOLTAGE = "surplus_line_voltage"
CONF_SURPLUS_START_THRESHOLD_W = "surplus_start_threshold_w"
CONF_SURPLUS_STOP_THRESHOLD_W = "surplus_stop_threshold_w"
CONF_SURPLUS_TARGET_OFFSET_W = "surplus_target_offset_w"
CONF_SURPLUS_START_DELAY_S = "surplus_start_delay_s"
CONF_SURPLUS_STOP_DELAY_S = "surplus_stop_delay_s"
CONF_SURPLUS_ADJUST_COOLDOWN_S = "surplus_adjust_cooldown_s"

SURPLUS_MODE_CLASSIC = "classic"
SURPLUS_MODE_ZERO_INJECTION = "zero_injection"
SURPLUS_MODES: tuple[str, ...] = (
    SURPLUS_MODE_CLASSIC,
    SURPLUS_MODE_ZERO_INJECTION,
)

DEFAULT_NAME = "Tuya EV Charger"
DEFAULT_PROTOCOL_VERSION = "3.5"
SUPPORTED_PROTOCOL_VERSIONS: tuple[str, ...] = ("3.3", "3.4", "3.5")
DEFAULT_SCAN_INTERVAL_SECONDS = 30
MIN_SCAN_INTERVAL_SECONDS = 5
MAX_SCAN_INTERVAL_SECONDS = 300
DEFAULT_SCAN_INTERVAL = timedelta(seconds=DEFAULT_SCAN_INTERVAL_SECONDS)

DEFAULT_SURPLUS_MODE_ENABLED = False
DEFAULT_SURPLUS_SENSOR_ENTITY_ID = ""
DEFAULT_SURPLUS_SENSOR_INVERTED = False
DEFAULT_SURPLUS_MODE = SURPLUS_MODE_CLASSIC
DEFAULT_SURPLUS_CURTAILMENT_SENSOR_ENTITY_ID = ""
DEFAULT_SURPLUS_CURTAILMENT_SENSOR_INVERTED = False
DEFAULT_SURPLUS_LINE_VOLTAGE = 230
MIN_SURPLUS_LINE_VOLTAGE = 180
MAX_SURPLUS_LINE_VOLTAGE = 260
DEFAULT_SURPLUS_START_THRESHOLD_W = 1600
DEFAULT_SURPLUS_STOP_THRESHOLD_W = 1200
MIN_SURPLUS_THRESHOLD_W = 0
MAX_SURPLUS_THRESHOLD_W = 22000
DEFAULT_SURPLUS_TARGET_OFFSET_W = 0
MIN_SURPLUS_TARGET_OFFSET_W = -5000
MAX_SURPLUS_TARGET_OFFSET_W = 5000
DEFAULT_SURPLUS_START_DELAY_S = 30
DEFAULT_SURPLUS_STOP_DELAY_S = 60
DEFAULT_SURPLUS_ADJUST_COOLDOWN_S = 20
MIN_SURPLUS_DELAY_S = 0
MAX_SURPLUS_DELAY_S = 900

PLATFORMS: tuple[Platform, ...] = (
    Platform.BUTTON,
    Platform.SENSOR,
    Platform.NUMBER,
    Platform.SWITCH,
)

ALLOWED_CURRENTS: tuple[int, ...] = (6, 8, 10, 13, 16)

DP_WORK_STATE = "101"
DP_CHARGER_INFO = "106"
DP_METRICS = "102"
DP_SELFTEST = "103"
DP_ALARM = "104"
DP_CHARGE_HISTORY = "105"
DP_ADJUST_CURRENT = "107"
DP_DOWNCOUNTER = "108"
DP_WORK_STATE_DEBUG = "109"
DP_DO_CHARGE = "140"
DP_DO_RESET = "141"
DP_CURRENT_TARGET = "150"
DP_MAX_CURRENT_CFG = "152"
DP_SOCKET_CFG = "154"
DP_NFC_CFG = "155"
DP_EARCH_FREE_CFG = "156"
DP_PRODUCT_VARIANT = "157"
DP_REBOOT = "142"
DP_HEARTBEAT = "188"
DP_NUM = "189"
