from __future__ import annotations

from datetime import timedelta

from homeassistant.const import Platform

DOMAIN = "tuya_ev_charger"

CONF_DEVICE_ID = "device_id"
CONF_LOCAL_KEY = "local_key"
CONF_PROTOCOL_VERSION = "protocol_version"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_NAME = "Tuya EV Charger"
DEFAULT_PROTOCOL_VERSION = "3.5"
SUPPORTED_PROTOCOL_VERSIONS: tuple[str, ...] = ("3.3", "3.4", "3.5")
DEFAULT_SCAN_INTERVAL_SECONDS = 30
MIN_SCAN_INTERVAL_SECONDS = 5
MAX_SCAN_INTERVAL_SECONDS = 300
DEFAULT_SCAN_INTERVAL = timedelta(seconds=DEFAULT_SCAN_INTERVAL_SECONDS)

PLATFORMS: tuple[Platform, ...] = (
    Platform.BUTTON,
    Platform.SENSOR,
    Platform.NUMBER,
    Platform.SWITCH,
)

ALLOWED_CURRENTS: tuple[int, ...] = (6, 8, 10, 13, 16)

DP_WORK_STATE = "101"
DP_CHARGER_INFO = "106"
DP_METRICS = "102"
DP_SELFTEST = "103"
DP_ALARM = "104"
DP_CHARGE_HISTORY = "105"
DP_ADJUST_CURRENT = "107"
DP_DOWNCOUNTER = "108"
DP_WORK_STATE_DEBUG = "109"
DP_DO_CHARGE = "140"
DP_DO_RESET = "141"
DP_CURRENT_TARGET = "150"
DP_MAX_CURRENT_CFG = "152"
DP_SOCKET_CFG = "154"
DP_NFC_CFG = "155"
DP_EARCH_FREE_CFG = "156"
DP_PRODUCT_VARIANT = "157"
DP_REBOOT = "142"
DP_HEARTBEAT = "188"
DP_NUM = "189"
