from __future__ import annotations

from datetime import timedelta

from homeassistant.const import Platform

DOMAIN = "tuya_ev_charger"

CONF_CHARGER_PROFILE = "charger_profile"
CONF_CHARGER_PROFILE_JSON = "charger_profile_json"
CONF_DEVICE_ID = "device_id"
CONF_LOCAL_KEY = "local_key"
CONF_PROTOCOL_VERSION = "protocol_version"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_SURPLUS_PROFILE = "surplus_profile"
CONF_SURPLUS_MODE_ENABLED = "surplus_mode_enabled"
CONF_SURPLUS_SENSOR_ENTITY_ID = "surplus_sensor_entity_id"
CONF_SURPLUS_SENSOR_INVERTED = "surplus_sensor_inverted"
CONF_SURPLUS_MODE = "surplus_mode"
CONF_SURPLUS_CURTAILMENT_SENSOR_ENTITY_ID = "surplus_curtailment_sensor_entity_id"
CONF_SURPLUS_CURTAILMENT_SENSOR_INVERTED = "surplus_curtailment_sensor_inverted"
CONF_SURPLUS_BATTERY_SOC_SENSOR_ENTITY_ID = "surplus_battery_soc_sensor_entity_id"
CONF_SURPLUS_BATTERY_SOC_HIGH_THRESHOLD_PCT = "surplus_battery_soc_high_threshold_pct"
CONF_SURPLUS_BATTERY_SOC_LOW_THRESHOLD_PCT = "surplus_battery_soc_low_threshold_pct"
CONF_SURPLUS_BATTERY_SOC_THRESHOLD_PCT = "surplus_battery_soc_threshold_pct"
CONF_SURPLUS_BATTERY_NET_DISCHARGE_SENSOR_ENTITY_ID = "surplus_battery_net_discharge_sensor_entity_id"
CONF_SURPLUS_BATTERY_NET_DISCHARGE_SENSOR_INVERTED = "surplus_battery_net_discharge_sensor_inverted"
CONF_SURPLUS_ALLOW_BATTERY_DISCHARGE_FOR_EV = "surplus_allow_battery_discharge_for_ev"
CONF_SURPLUS_MAX_BATTERY_DISCHARGE_FOR_EV_W = "surplus_max_battery_discharge_for_ev_w"
CONF_SURPLUS_LINE_VOLTAGE = "surplus_line_voltage"
CONF_SURPLUS_START_THRESHOLD_W = "surplus_start_threshold_w"
CONF_SURPLUS_STOP_THRESHOLD_W = "surplus_stop_threshold_w"
CONF_SURPLUS_TARGET_OFFSET_W = "surplus_target_offset_w"
CONF_SURPLUS_START_DELAY_S = "surplus_start_delay_s"
CONF_SURPLUS_STOP_DELAY_S = "surplus_stop_delay_s"
CONF_SURPLUS_ADJUST_COOLDOWN_S = "surplus_adjust_cooldown_s"
CONF_SURPLUS_ADJUST_UP_COOLDOWN_S = "surplus_adjust_up_cooldown_s"
CONF_SURPLUS_ADJUST_DOWN_COOLDOWN_S = "surplus_adjust_down_cooldown_s"
CONF_SURPLUS_RAMP_STEP_A = "surplus_ramp_step_a"
CONF_SURPLUS_MIN_RUN_TIME_S = "surplus_min_run_time_s"
CONF_SURPLUS_MAX_SESSION_DURATION_MIN = "surplus_max_session_duration_min"
CONF_SURPLUS_MAX_SESSION_ENERGY_KWH = "surplus_max_session_energy_kwh"
CONF_SURPLUS_MAX_SESSION_END_TIME = "surplus_max_session_end_time"
CONF_SURPLUS_FORECAST_MODE_ENABLED = "surplus_forecast_mode_enabled"
CONF_SURPLUS_FORECAST_SENSOR_ENTITY_ID = "surplus_forecast_sensor_entity_id"
CONF_SURPLUS_FORECAST_WEIGHT_PCT = "surplus_forecast_weight_pct"
CONF_SURPLUS_FORECAST_SMOOTHING_S = "surplus_forecast_smoothing_s"
CONF_SURPLUS_FORECAST_DROP_GUARD_W = "surplus_forecast_drop_guard_w"
CONF_SURPLUS_DRY_RUN_CONTINUOUS_ENABLED = "surplus_dry_run_continuous_enabled"
CONF_SURPLUS_DEPARTURE_MODE_ENABLED = "surplus_departure_mode_enabled"
CONF_SURPLUS_DEPARTURE_TIME = "surplus_departure_time"
CONF_SURPLUS_DEPARTURE_TARGET_ENERGY_KWH = "surplus_departure_target_energy_kwh"

SERVICE_FORCE_CHARGE_FOR = "force_charge_for"
SERVICE_DRY_RUN_SURPLUS = "dry_run_surplus"
SERVICE_PAUSE_SURPLUS = "pause_surplus"
SERVICE_PROFILE_ASSISTANT = "profile_assistant"
SERVICE_SET_SURPLUS_PROFILE = "set_surplus_profile"

SURPLUS_PROFILE_ECO = "eco"
SURPLUS_PROFILE_BALANCED = "balanced"
SURPLUS_PROFILE_FAST = "fast"
# Legacy aliases kept for backward compatibility.
SURPLUS_PROFILE_AGGRESSIVE = "aggressive"
SURPLUS_PROFILE_CONSERVATIVE = "conservative"
SURPLUS_PROFILES: tuple[str, ...] = (
    SURPLUS_PROFILE_ECO,
    SURPLUS_PROFILE_BALANCED,
    SURPLUS_PROFILE_FAST,
)

CHARGER_PROFILE_DEPOW_V2 = "depow_v2"
CHARGER_PROFILE_GENERIC_V1 = "generic_v1"
CHARGER_PROFILE_CUSTOM_JSON = "custom_json"
CHARGER_PROFILES: tuple[str, ...] = (
    CHARGER_PROFILE_CUSTOM_JSON,
    CHARGER_PROFILE_DEPOW_V2,
    CHARGER_PROFILE_GENERIC_V1,
)

SURPLUS_MODE_CLASSIC = "classic"
SURPLUS_MODE_ZERO_INJECTION = "zero_injection"
SURPLUS_MODES: tuple[str, ...] = (
    SURPLUS_MODE_CLASSIC,
    SURPLUS_MODE_ZERO_INJECTION,
)

DEFAULT_NAME = "Tuya EV Charger"
DEFAULT_PROTOCOL_VERSION = "3.5"
DEFAULT_CHARGER_PROFILE = CHARGER_PROFILE_DEPOW_V2
DEFAULT_CHARGER_PROFILE_JSON = ""
SUPPORTED_PROTOCOL_VERSIONS: tuple[str, ...] = ("3.3", "3.4", "3.5")
DEFAULT_SCAN_INTERVAL_SECONDS = 30
MIN_SCAN_INTERVAL_SECONDS = 5
MAX_SCAN_INTERVAL_SECONDS = 300
DEFAULT_SCAN_INTERVAL = timedelta(seconds=DEFAULT_SCAN_INTERVAL_SECONDS)
DEFAULT_SURPLUS_PROFILE = SURPLUS_PROFILE_BALANCED

DEFAULT_SURPLUS_MODE_ENABLED = False
DEFAULT_SURPLUS_SENSOR_ENTITY_ID = ""
DEFAULT_SURPLUS_SENSOR_INVERTED = False
DEFAULT_SURPLUS_MODE = SURPLUS_MODE_CLASSIC
DEFAULT_SURPLUS_CURTAILMENT_SENSOR_ENTITY_ID = ""
DEFAULT_SURPLUS_CURTAILMENT_SENSOR_INVERTED = False
DEFAULT_SURPLUS_BATTERY_SOC_SENSOR_ENTITY_ID = ""
DEFAULT_SURPLUS_BATTERY_SOC_HIGH_THRESHOLD_PCT = 95
DEFAULT_SURPLUS_BATTERY_SOC_LOW_THRESHOLD_PCT = 90
DEFAULT_SURPLUS_BATTERY_SOC_THRESHOLD_PCT = 95
DEFAULT_SURPLUS_BATTERY_NET_DISCHARGE_SENSOR_ENTITY_ID = ""
DEFAULT_SURPLUS_BATTERY_NET_DISCHARGE_SENSOR_INVERTED = False
DEFAULT_SURPLUS_ALLOW_BATTERY_DISCHARGE_FOR_EV = True
DEFAULT_SURPLUS_MAX_BATTERY_DISCHARGE_FOR_EV_W = 22000
MIN_SURPLUS_BATTERY_SOC_THRESHOLD_PCT = 0
MAX_SURPLUS_BATTERY_SOC_THRESHOLD_PCT = 100
DEFAULT_SURPLUS_LINE_VOLTAGE = 230
MIN_SURPLUS_LINE_VOLTAGE = 180
MAX_SURPLUS_LINE_VOLTAGE = 260
DEFAULT_SURPLUS_START_THRESHOLD_W = 1600
DEFAULT_SURPLUS_STOP_THRESHOLD_W = 1200
MIN_SURPLUS_THRESHOLD_W = 0
MAX_SURPLUS_THRESHOLD_W = 22000
MIN_SURPLUS_MAX_BATTERY_DISCHARGE_FOR_EV_W = 0
MAX_SURPLUS_MAX_BATTERY_DISCHARGE_FOR_EV_W = 22000
DEFAULT_SURPLUS_TARGET_OFFSET_W = 0
MIN_SURPLUS_TARGET_OFFSET_W = -5000
MAX_SURPLUS_TARGET_OFFSET_W = 5000
DEFAULT_SURPLUS_START_DELAY_S = 30
DEFAULT_SURPLUS_STOP_DELAY_S = 60
DEFAULT_SURPLUS_ADJUST_COOLDOWN_S = 20
DEFAULT_SURPLUS_ADJUST_UP_COOLDOWN_S = 20
DEFAULT_SURPLUS_ADJUST_DOWN_COOLDOWN_S = 10
DEFAULT_SURPLUS_RAMP_STEP_A = 1
DEFAULT_SURPLUS_MIN_RUN_TIME_S = 0
DEFAULT_SURPLUS_MAX_SESSION_DURATION_MIN = 0
DEFAULT_SURPLUS_MAX_SESSION_ENERGY_KWH = 0.0
DEFAULT_SURPLUS_MAX_SESSION_END_TIME = ""
DEFAULT_SURPLUS_FORECAST_MODE_ENABLED = False
DEFAULT_SURPLUS_FORECAST_SENSOR_ENTITY_ID = ""
DEFAULT_SURPLUS_FORECAST_WEIGHT_PCT = 40
DEFAULT_SURPLUS_FORECAST_SMOOTHING_S = 120
DEFAULT_SURPLUS_FORECAST_DROP_GUARD_W = 500
DEFAULT_SURPLUS_DRY_RUN_CONTINUOUS_ENABLED = True
DEFAULT_SURPLUS_DEPARTURE_MODE_ENABLED = False
DEFAULT_SURPLUS_DEPARTURE_TIME = ""
DEFAULT_SURPLUS_DEPARTURE_TARGET_ENERGY_KWH = 0.0
MIN_SURPLUS_DELAY_S = 0
MAX_SURPLUS_DELAY_S = 3600
MIN_SURPLUS_RAMP_STEP_A = 1
MAX_SURPLUS_RAMP_STEP_A = 16
MIN_SURPLUS_SESSION_DURATION_MIN = 0
MAX_SURPLUS_SESSION_DURATION_MIN = 1440
MIN_SURPLUS_SESSION_ENERGY_KWH = 0.0
MAX_SURPLUS_SESSION_ENERGY_KWH = 200.0
MIN_SURPLUS_DEPARTURE_TARGET_ENERGY_KWH = 0.0
MAX_SURPLUS_DEPARTURE_TARGET_ENERGY_KWH = 200.0
MIN_SURPLUS_END_TIME_LEN = 0
MAX_SURPLUS_END_TIME_LEN = 5
MIN_SURPLUS_FORECAST_WEIGHT_PCT = 0
MAX_SURPLUS_FORECAST_WEIGHT_PCT = 100
MIN_SURPLUS_FORECAST_DROP_GUARD_W = 0
MAX_SURPLUS_FORECAST_DROP_GUARD_W = 10000

PLATFORMS: tuple[Platform, ...] = (
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.SENSOR,
    Platform.NUMBER,
    Platform.SELECT,
    Platform.SWITCH,
)

ALLOWED_CURRENTS: tuple[int, ...] = (6, 8, 10, 13, 16)

DP_WORK_STATE = "101"
DP_CHARGER_INFO = "106"
DP_METRICS = "102"
DP_SELFTEST = "103"
DP_ALARM = "104"
DP_CHARGE_HISTORY = "105"
DP_ADJUST_CURRENT = "107"
DP_DOWNCOUNTER = "108"
DP_WORK_STATE_DEBUG = "109"
DP_DO_CHARGE = "140"
DP_DO_RESET = "141"
DP_CURRENT_TARGET = "150"
DP_MAX_CURRENT_CFG = "152"
DP_SOCKET_CFG = "154"
DP_NFC_CFG = "155"
DP_EARCH_FREE_CFG = "156"
DP_PRODUCT_VARIANT = "157"
DP_REBOOT = "142"
DP_HEARTBEAT = "188"
DP_NUM = "189"
